import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loader from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "next-js-recipe-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Suspense fallback={<Loader />}>
            {children}
          </Suspense>
        </div>
      </body>
    </html>
  );
}
